name: Run Specific Module Tests
on:
  workflow_dispatch:
   inputs:
      Module:
        description: Select a module for execution
        default: ''
        required: true
        type: choice
        options:
        - Test1Suite
        - Test2Suite


jobs:
  RunTests:
    runs-on: windows-latest
   
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - uses: actions/checkout@v2
     
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
         
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
         maven-version: 3.8.2
         
      - name: Started ${{github.event.inputs.Module}} Execution
        working-directory: ./WORKSPACELOCATION
        run: mvn clean -DSuiteName=@${{github.event.inputs.Module}} verify
     
      - name: Generate Execution ${{github.event.inputs.Module}} Report
        if : ${{always()}}
        working-directory: ./WORKSPACELOCATION
        run: mvn serenity::aggregate
       
      - name: Upload Execution Report
        if : ${{always()}}
        uses: actions/upload-artifact@v3
        with:
          name: ${{github.event.inputs.Module}}-Execution-Report
          path: D:/REPORTLOCATION/target
